version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: friday
      time: "16:00"
      timezone: Asia/Kolkata
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "@types/node"
        versions:
          - ">=24.0.0"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: friday
      time: "16:00"
      timezone: Asia/Kolkata
    open-pull-requests-limit: 5