version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: friday
      time: "16:00"
      timezone: Asia/Kolkata
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: friday
      time: "16:00"
      timezone: Asia/Kolkata
    open-pull-requests-limit: 5