name: Upload Test Reports

runs:
  using: composite
  steps:
    - uses: mikepenz/action-junit-report@v6
      if: success() || failure() # always run even if the previous step fails
      with:
        report_paths: '**/build/junit-report.xml'

