name: Dependabot
on:
  pull_request:
    branches:
      - dependabot/**

permissions:
  pull-requests: write
  contents: write
  id-token: write
  actions: read

jobs:
  build:
    name: Validate Dependabot Changes
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]'}}
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/workflows/composite/pnpm-setup
      - run: pnpm test
      - uses: ./.github/workflows/composite/upload-test-report
      - run: pnpm build
  merge:
    name: Auto Merge
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]'}}
    steps:
      - uses: actions/checkout@v6
      - run: gh pr merge --merge ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: "${{secrets.GITHUB_TOKEN}}"
